name: Postman Workflow

on: [push]

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run path/to/collection.json \
            -e path/to/environment.json \
            --globals path/to/globals.json \
            --reporters cli,junit \
            --reporter-junit-export results.xml
