name: Postman Workflow

on: [push]

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run ./postman/collection.json \
          -e ./postman/environment.json \
          --globals ./postman/globals.json \
          --reporters cli,junit,json \
          --reporter-junit-export ./postman/reports/results.xml \
          --reporter-json-export ./postman/reports/results.json \
          --suppress-exit-code

